### ISSUE TITLE
As a user, I should be able to easily use the global search bar and designate what type of matching I desire.

### ISSUE THREAD

**Issue by clairebingham** [colin19/Parkd#51]
-Currently, the dropdown for the global search specifies “OR” and “ALL”. Maybe change “all” to AND or put a more plain-english description of the type of search. A user unfamiliar with “OR” and “AND” methods of searching may be confused by this.
-Also, the dropdown defaults to “OR” but this is the second option in the dropdown. I would prefer to see the first option defaulted.

**Comment by GuanSuns** [comment]
We replace the "OR" and "ALL" with a plain-text description: "OR: Match one or more keywords", "AND: Match all the keywords"
