### ISSUE TITLE
As a user, I should be able to easily navigate to related photos from a park’s detail page.

### ISSUE THREAD

**Issue by clairebingham** [colin19/Parkd#54]
-Currently, on the detail pages for parks, the related photo carousel only includes 1 link to view more photos on the first carousel slide. This slides away within seconds, and the rest of the photos don’t include links or ways of navigating to the photo detail page.
-Ex: http://parkd.us/parks/detail?id=14

**Comment by GuanSuns** [comment]
added link to photo detail in park detail page
