### ISSUE TITLE
As a user, I should have a pleasant experience on the about page

### ISSUE THREAD

**Issue by clairebingham** [colin19/Parkd#57]
-Some minor fixes that would be nice on the about page would be to make the data sources clickable links, instead of just unclickable URL text (the links section does this, but not the data sources section). Also, the total number of unit tests under the Stats section still displays 0, although individual group members do have multiple unit tests listed. Lastly, it might look nice to split the group member cards up into 2 rows instead of 1 to avoid the vertical stretching happening on desktop.

**Comment by GuanSuns** [comment]
added clickable links, rearranged group info rows, added links to tools, fixed unit tests count

**Comment by dalcoz** [comment]
The way we have it now is suboptimal for a few reasons and I want to change it back to the way it was before, but not before figuring out what you meant first.
