### ISSUE TITLE
As a user, I would like to see a custom favicon displayed on my browser tab.

### ISSUE THREAD

**Issue by clairebingham** [colin19/Parkd#58]
-Super quick fix that could improve the look of the site a lot in the browser, maybe you could do a tiny picture of a food truck or something!

**Comment by GuanSuns** [comment]
added new icon

**Comment by GuanSuns** [comment]
<img width="104" alt="screen shot 2018-04-15 at 5 36 26 pm" src="https://user-images.githubusercontent.com/18614719/38784220-84d227e6-40d4-11e8-9699-25086a51caa4.png">

**Comment by clairebingham** [comment]
luv it!!!!
